version: "3.7"
# services:
#   app:
#     build: .
#     container_name: rentalx
#     restart: always
#     ports:
#       - 3333:3333
#     volumes:
#       - .:/usr/app
#     network_mode: host
#   database_ignite:
#     image: postgres
#     container_name: database_ignite
#     restart: always
#     ports:
#       - 5432:5432
#     volumes:
#       - ./.docker/pgdata:/var/lib/postgresql/data
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: rentalx
#     network_mode: host


